// GENERATED by scripts/build-academy-quizzes.mjs — edit supabase/quiz-source.private.json instead.
// Correct answers are intentionally absent; grading happens in the submit_quiz() database function.

export type QuizQuestion = { question: string; options: string[] };

export const PASS_PERCENT = 80;

export const quizzes: Record<string, Record<string, QuizQuestion[]>> = {
  "en": {
    "10": [
      {
        "question": "Which job is AI image tools still often bad at?",
        "options": [
          "Turning a description into a brand-new image",
          "Spelling words correctly inside an image",
          "Making a picture in a watercolor style",
          "Removing the background from a product photo"
        ]
      },
      {
        "question": "You want a picture of your actual storefront for your website. What's the best approach?",
        "options": [
          "Take a real photo and use AI to improve the lighting or crop",
          "Ask AI to create a version that looks bigger than it is",
          "Use a stock photo of a similar shop and add your logo",
          "Describe your shop to an image generator and use its picture"
        ]
      },
      {
        "question": "Which part is missing from this description: \"a golden retriever in a party hat, cartoon style, square\"?",
        "options": [
          "Setting, light and mood",
          "Shape and size",
          "Style",
          "Subject"
        ]
      },
      {
        "question": "What is a deepfake?",
        "options": [
          "An illustration made in a realistic style instead of a cartoon one",
          "A photo with the background removed by an AI tool",
          "AI-made media showing a real person doing or saying something they didn't",
          "Any image that has been edited with a filter or color correction"
        ]
      },
      {
        "question": "Which use of AI visuals is honest?",
        "options": [
          "AI-made customer photos used next to real reviews",
          "A product image showing features the product doesn't have",
          "A clearly illustrated flyer background for a bake sale",
          "\"Before and after\" photos created to show results you haven't had"
        ]
      }
    ],
    "11": [
      {
        "question": "What's the first step of the brain dump planning method?",
        "options": [
          "Open your calendar and block time for your most important task",
          "Write down every task and worry in any order, without organizing it",
          "Ask the AI which tasks you should drop this week",
          "Rank every task from most to least urgent before typing it in"
        ]
      },
      {
        "question": "Why should you tell the AI how long tasks really take you?",
        "options": [
          "Without times it will refuse to make a plan at all",
          "It needs the times to connect to your calendar automatically",
          "It doesn't know, and plans without that information are often unrealistic",
          "It uses the times to decide which tasks to remove for you"
        ]
      },
      {
        "question": "What's a safe way to get help with your budget?",
        "options": [
          "Share your online banking login so it can check balances",
          "Paste your full bank statements so it sees every detail",
          "Describe income and spending in rough categories",
          "Give it your card numbers to track spending by card"
        ]
      },
      {
        "question": "You're using AI to understand a health question. What's the right approach?",
        "options": [
          "Follow its advice instead of seeing a doctor to save time",
          "Ask it to diagnose you, then buy the medicine it suggests",
          "Use it to understand options and prepare questions for your doctor",
          "Avoid AI completely, since it can't explain anything medical"
        ]
      },
      {
        "question": "Which is the best way to learn a new topic with AI?",
        "options": [
          "Read its first explanation and trust it without checking",
          "Ask it to complete your homework so you can study the answers",
          "Ask it to explain simply, then quiz you and check important facts",
          "Ask for the longest, most detailed explanation it can write"
        ]
      }
    ],
    "12": [
      {
        "question": "Before adding any AI to answer customers, what should you do first?",
        "options": [
          "Choose the most advanced AI phone system available",
          "Turn off your current contact options so everything goes through AI",
          "Ask the AI to guess what your customers will probably ask",
          "List the questions customers actually ask and write clear answers"
        ]
      },
      {
        "question": "Which customer message should always go to a person?",
        "options": [
          "\"Do you serve my zip code?\"",
          "\"What are your hours on Saturday?\"",
          "\"Can you send me the link to book?\"",
          "A customer upset about a job and asking for a refund"
        ]
      },
      {
        "question": "What should a good AI chat assistant do when it doesn't know an answer?",
        "options": [
          "Answer a different question it does know about",
          "Give its best guess so the customer isn't kept waiting",
          "End the chat politely and ask them to try again later",
          "Say it isn't sure and get the customer to a person"
        ]
      },
      {
        "question": "Why is it important to tell customers they're talking to AI?",
        "options": [
          "It lets the AI skip the handoff rules",
          "Customers prefer AI, so it works as a selling point",
          "It makes the AI's answers more accurate",
          "It builds trust, and in many places it's becoming a legal requirement"
        ]
      },
      {
        "question": "What's a knowledge base?",
        "options": [
          "The AI company's own database of facts about the internet",
          "A report showing how many calls the AI answered each week",
          "The list of every customer who has chatted with your business",
          "The written facts an AI assistant answers from, like hours, prices and policies"
        ]
      }
    ],
    "13": [
      {
        "question": "What should you do before recording a meeting for AI notes?",
        "options": [
          "Nothing, as long as the recording stays on your phone",
          "Only ask permission if a customer is on the call",
          "Tell everyone and get their OK",
          "Record it secretly so people speak naturally"
        ]
      },
      {
        "question": "An AI meeting summary says the client agreed to $4,500. What should you do?",
        "options": [
          "Check the amount against what you remember before sending",
          "Delete the summary and write everything from scratch",
          "Send it right away, since transcripts are always accurate",
          "Round it to $5,000 to be safe"
        ]
      },
      {
        "question": "What's the best way to get AI to draft a new proposal that matches your style?",
        "options": [
          "Paste a proposal that worked well and ask it to use it as a template",
          "Ask for the longest proposal possible so nothing is missing",
          "Ask for \"a professional proposal\" and fix the style afterward",
          "Let it choose the prices so the proposal looks complete"
        ]
      },
      {
        "question": "AI drafted a contract for a new client. What's the right next step?",
        "options": [
          "Ask a second AI tool to confirm it is legal",
          "Have a lawyer review it before anyone signs",
          "Sign it right away, since AI knows the law",
          "Send it as is but add \"made with AI\" at the bottom"
        ]
      },
      {
        "question": "A task repeats every day and follows clear rules. Where can you learn to make it run automatically?",
        "options": [
          "Module 02, AI Tools & Automation",
          "Module 11, Plan Your Week & Everyday Life",
          "Module 10, Make Images & Videos",
          "Module 08, Reviews & Reputation"
        ]
      }
    ],
    "14": [
      {
        "question": "What makes AI's business advice better?",
        "options": [
          "Asking the same question several times and picking the boldest answer",
          "Giving it the full picture and asking it to question you first",
          "Asking a one-line question so it isn't influenced",
          "Telling it to agree with your plan so you stay motivated"
        ]
      },
      {
        "question": "AI gives you a competitor's prices from a web search. What should you do?",
        "options": [
          "Open the sources to check they're accurate and current",
          "Assume they're too low and add 10%",
          "Use them right away, since web search is always up to date",
          "Ignore them, since AI can never research competitors"
        ]
      },
      {
        "question": "AI works out that a price increase will earn you more. What's the smart next step?",
        "options": [
          "Check the math yourself or in a spreadsheet",
          "Ask it to round the numbers so they look cleaner",
          "Raise prices tomorrow, since AI is good at math",
          "Lower prices instead to be safe"
        ]
      },
      {
        "question": "What's a good way to test a new offer before investing in it?",
        "options": [
          "Build the whole thing, then announce it to everyone",
          "Offer it to a few customers first and see who says yes",
          "Ask AI whether customers will like it and trust the answer",
          "Copy a competitor's offer exactly, since it's already proven"
        ]
      },
      {
        "question": "Where can you find a better reason to choose a business opportunity than an AI guess?",
        "options": [
          "Short conversations with real customers",
          "A longer and more detailed AI answer",
          "The opportunity that sounds the most exciting",
          "Whatever the most popular AI tool recommends"
        ]
      }
    ],
    "01": [
      {
        "question": "What is a 'hallucination' in AI?",
        "options": [
          "When an AI repeats its training data word for word instead of writing something new",
          "When an AI mixes up instructions from earlier in a long conversation with new ones",
          "When an AI gives a different answer each time you ask it the same question",
          "When an AI states false information confidently, such as a fake statistic or source"
        ]
      },
      {
        "question": "Which of these is an example of predictive AI?",
        "options": [
          "A chatbot rewriting your product description in a friendlier, shorter tone",
          "An AI assistant turning your meeting notes into a follow-up email for a lead",
          "An image tool creating three versions of an ad graphic in different sizes",
          "An ad platform deciding which people are most likely to click your ad"
        ]
      },
      {
        "question": "What's the best starting point for using AI in your marketing?",
        "options": [
          "Pick the most popular AI tool and find ways to use it everywhere",
          "Have AI write a month of social posts first, since content is the quickest win",
          "Automate the tasks that take the most clicks, starting with customer messages",
          "Find the funnel stage where you're losing the most time or customers"
        ]
      },
      {
        "question": "Which task should always have human approval before going live?",
        "options": [
          "An internal summary of a lead form for the sales owner",
          "Tagging incoming messages as sales, support or spam",
          "A list of blog topic ideas for the marketing team",
          "A promotional email that your customers will read"
        ]
      },
      {
        "question": "Which use of AI is NOT acceptable?",
        "options": [
          "Drafting replies to common customer questions for a person to review",
          "Summarizing real customer reviews to find common themes",
          "Brainstorming headline and subject line ideas for a promotion",
          "Generating realistic customer testimonials for your ads"
        ]
      }
    ],
    "02": [
      {
        "question": "In an automation workflow, what is a 'trigger'?",
        "options": [
          "The step that sends information to an AI model and uses its reply",
          "The event that starts the workflow, like a new form submission",
          "The action that happens after a lead is saved, like a confirmation email",
          "A rule that decides whether the workflow continues, like a minimum budget"
        ]
      },
      {
        "question": "What's the best way to make an AI step in a workflow predictable?",
        "options": [
          "Ask the AI to explain its reasoning in a full paragraph before each answer",
          "Give the AI more creative freedom so it can handle any reply it gets",
          "Require a fixed output format and add a fallback for unexpected replies",
          "Use the newest AI model, since newer models always follow instructions"
        ]
      },
      {
        "question": "What should you do BEFORE automating a process?",
        "options": [
          "Choose the automation platform with the most app integrations",
          "Connect every app the team uses",
          "Map exactly how the process works today, step by step",
          "Remove human approval steps so the workflow can run on its own"
        ]
      },
      {
        "question": "When evaluating a new AI tool, which question matters most?",
        "options": [
          "How many features does it have compared with other tools on the market?",
          "Do its demo examples look better than what our current tools produce?",
          "Which specific task does it improve, and can I measure the difference?",
          "Is it the newest release, and how many businesses are already using it?"
        ]
      },
      {
        "question": "Why keep a human approval step in customer-facing workflows at first?",
        "options": [
          "To slow the workflow down so customers don’t notice the replies are automated",
          "Because automation platforms won’t send anything to customers without one",
          "To catch mistakes before customers see them while you confirm the AI output is reliable",
          "Because AI output should never reach customers directly, even after months of consistently good results"
        ]
      }
    ],
    "03": [
      {
        "question": "Which prompt will most likely get the best result?",
        "options": [
          "A short prompt so the AI can fill in the details with its own creativity",
          "\"Write a great post about our business that will go viral on Instagram.\"",
          "A prompt that sets out the role, context, task, format and constraints",
          "A long paragraph about the business’s history with no task stated"
        ]
      },
      {
        "question": "What is 'few-shot prompting'?",
        "options": [
          "Asking the AI for several short drafts and picking the best one",
          "Writing prompts with as few words as possible to save on usage costs",
          "Including a few examples in the prompt of what good output looks like",
          "Breaking a big task into a few smaller prompts that run one after another"
        ]
      },
      {
        "question": "The AI gives you a weak draft. What's the best next step?",
        "options": [
          "Click regenerate a few times until a stronger version appears on its own",
          "Switch to a different AI tool, since the first one has shown it can’t handle this kind of task",
          "Identify what was missing from the prompt, add it and give specific feedback",
          "Reply \"make it better\" so the AI knows to improve on its first attempt"
        ]
      },
      {
        "question": "What belongs in a brand voice guide?",
        "options": [
          "A list of the AI tools the team uses and who has access to each one",
          "Voice traits with examples, words to use and avoid, and rules on claims",
          "Your logo files, brand colors and the fonts approved for every platform",
          "Competitor taglines to borrow so your messaging feels familiar to customers"
        ]
      },
      {
        "question": "Why build a shared prompt library?",
        "options": [
          "It turns one person's best-performing prompts into the team's standard",
          "It replaces the need for a content strategy, since prompts set the topics",
          "It means AI output from saved prompts no longer needs a human edit",
          "Most AI tools only remember prompts that are saved in a shared library"
        ]
      }
    ],
    "04": [
      {
        "question": "What should come first when planning AI-assisted content?",
        "options": [
          "A competitor’s content calendar to use as a starting point",
          "Which AI tool and image style to use for the brand",
          "The business goal and a specific target audience to reach",
          "How many posts to publish each day on each platform"
        ]
      },
      {
        "question": "What are content pillars?",
        "options": [
          "Three to five recurring themes that connect audience needs with what you sell",
          "The platforms where you publish most often, such as Instagram and Google",
          "A fixed set of branded hashtags added to every post so content is easy to find",
          "The three to five posts that got the most engagement, reused as templates"
        ]
      },
      {
        "question": "In the repurposing pyramid, what does the pillar piece need most?",
        "options": [
          "The highest possible word count so it can be split into more pieces",
          "Real expertise, first-hand experience or stories from the business",
          "A trending format or audio track so it reaches people beyond your followers",
          "As many keywords as possible so it ranks for every related search"
        ]
      },
      {
        "question": "What kind of content does Google say it rewards?",
        "options": [
          "Long pages that use the main keyword in every heading and paragraph",
          "Helpful, reliable, people-first content, however it was produced",
          "A separate page for every city served, each with the same text and the city swapped",
          "Content written by people, since Google lowers the ranking of anything AI-assisted"
        ]
      },
      {
        "question": "Which step in the AI content workflow protects quality the most?",
        "options": [
          "The human edit and fact-check before publishing",
          "Scheduling posts for the best time of day",
          "Running every draft through an AI grammar checker",
          "Generating many variations to choose from"
        ]
      }
    ],
    "05": [
      {
        "question": "Which is a 'decision metric' rather than a vanity metric?",
        "options": [
          "Video views",
          "Cost per lead",
          "Total impressions",
          "Follower growth"
        ]
      },
      {
        "question": "200 people visit a landing page and 10 book a call. What's the conversion rate?",
        "options": [
          "5%",
          "2%",
          "10%",
          "20%"
        ]
      },
      {
        "question": "Before uploading a data export to an AI tool, you should:",
        "options": [
          "Convert it to a PDF so the AI can’t change the original numbers",
          "Remove personal information like names, emails and phone numbers",
          "Add every column you have so the AI has as much context as possible",
          "Merge cells and add colors so the AI can read the structure more easily"
        ]
      },
      {
        "question": "An AI tool reports a surprising number from your data. What should you do?",
        "options": [
          "Share it with the team right away so decisions can be made quickly",
          "Ask it to explain the calculation and spot-check the number yourself",
          "Ask the same question again and use the number if it comes back the same",
          "Trust it, since AI tools calculate numbers more reliably than spreadsheets"
        ]
      },
      {
        "question": "What makes a good A/B test?",
        "options": [
          "Changing one thing at a time and waiting for enough data",
          "Changing everything at once to find a winner faster",
          "Testing two ideas without writing down what you expect to happen",
          "Stopping as soon as one version gets a few more clicks"
        ]
      }
    ],
    "06": [
      {
        "question": "What does it mean to keep a 'human in the loop'?",
        "options": [
          "Customers are asked to approve AI-written posts before they are published",
          "Only one person on the team uses AI tools, so the output stays consistent",
          "A person types every message, and AI is only used for internal research",
          "A person reviews and approves important or customer-facing AI output"
        ]
      },
      {
        "question": "Which is the strongest reason to start with one small, frequent workflow?",
        "options": [
          "A small workflow doesn’t need testing, so it can go live the same day",
          "Small workflows are free on most automation platforms, so there’s no cost",
          "Large workflows can’t include AI steps until a small one has run first",
          "It saves real time with low risk while you learn what can go wrong"
        ]
      },
      {
        "question": "Which prompt part tells the AI what to avoid?",
        "options": [
          "Context",
          "Examples",
          "Output format",
          "Constraints"
        ]
      },
      {
        "question": "Which approach is most likely to hurt your search visibility?",
        "options": [
          "Answering real customer questions clearly",
          "Adding first-hand project photos and short captions to your service pages",
          "Keeping business details consistent across the web",
          "Publishing hundreds of thin, near-identical AI pages"
        ]
      },
      {
        "question": "What's the best use of AI for audience research?",
        "options": [
          "Pasting full customer emails, names and phone numbers in so the AI sees everything",
          "Asking AI to invent detailed customer personas, with names and jobs, when you don’t have real data yet",
          "Writing sample reviews with AI and posting them to see which ones get reactions",
          "Finding common questions and exact phrases in anonymized reviews and customer messages"
        ]
      },
      {
        "question": "Customer lifetime value (LTV) compared with customer acquisition cost (CAC) should be:",
        "options": [
          "Lower than CAC while the business is growing quickly",
          "About equal to CAC, so marketing pays for itself",
          "Unrelated to CAC, since they measure different things",
          "Much higher than CAC, as it is in a healthy business"
        ]
      },
      {
        "question": "What should a weekly marketing report lead to?",
        "options": [
          "A full list of every metric so nothing is missed",
          "A record of results to look back on at year end",
          "A chart of follower growth to share with the owner",
          "Specific decisions and actions for the next week"
        ]
      },
      {
        "question": "A website chat assistant answers customer questions. What's required for responsible use?",
        "options": [
          "Let it offer discounts on its own so it can close sales faster",
          "Give it a staff name and photo so customers feel more comfortable",
          "Keep it out of the privacy policy, since it doesn’t store any data",
          "Make clear it's automated and give an easy way to reach a person"
        ]
      },
      {
        "question": "Which statement about AI tools is true?",
        "options": [
          "Their output only needs editing when the prompt was written badly",
          "They learn your business automatically after you use them for a few weeks",
          "They check facts against the web before every answer, so their claims can be trusted as written",
          "They produce text that sounds right but can be wrong, so claims must be verified"
        ]
      },
      {
        "question": "What is the purpose of a North Star metric?",
        "options": [
          "To replace every other metric so the team only ever looks at one number",
          "To set the long-term vision statement that guides the brand’s content",
          "To track as many numbers as possible so no part of the funnel is missed",
          "To focus the team on the one number that best represents current success"
        ]
      }
    ],
    "07": [
      {
        "question": "Which three things does Google say local results are based on?",
        "options": [
          "Number of posts, photos and keywords",
          "Relevance, distance and prominence",
          "Price, opening hours and photos",
          "Ad spend, website age and review count"
        ]
      },
      {
        "question": "A barbershop's profile name is \"Brancato Barbershop Best Haircuts Boston\". What's the problem?",
        "options": [
          "Adding keywords to the name breaks Google's rules and can get the profile suspended",
          "Profile names can’t include a city, so Boston has to move to the address field",
          "The name is too long, and Google cuts off anything after the first three words",
          "Nothing — adding the city and service to the name helps it rank for those searches"
        ]
      },
      {
        "question": "Which single setting matters most for relevance in a Google Business Profile?",
        "options": [
          "The business description",
          "The primary category",
          "The number of posts",
          "The cover photo"
        ]
      },
      {
        "question": "What is a citation in local SEO?",
        "options": [
          "A link from another website to yours, which Google counts as a vote of trust",
          "A customer quote or review that the business shows on its own website",
          "Any place online that lists the business's name, address and phone number",
          "A warning from Google when a profile breaks its rules about names or reviews"
        ]
      },
      {
        "question": "The business moved last year. Yelp and Facebook still show the old address. Why fix it?",
        "options": [
          "Old addresses help the business appear in two neighborhoods’ searches until it’s established in the new one",
          "It only matters for businesses that run Google or Facebook ads",
          "Matching details everywhere help Google trust which information is right",
          "Only Google’s own data matters, so the other sites don’t need fixing"
        ]
      }
    ],
    "08": [
      {
        "question": "Which of these is allowed when asking for Google reviews?",
        "options": [
          "Offering 10% off to customers who leave a 5-star review",
          "Asking every customer the same way, with a short review link",
          "Asking only the customers who said they were happy with the visit",
          "Having staff post reviews from their own accounts about real jobs"
        ]
      },
      {
        "question": "What is review gating?",
        "options": [
          "Reporting reviews that break Google’s rules, such as spam or conflicts of interest, so they’re removed",
          "Replying to every review within a day so unhappy customers don’t post more",
          "Asking only happy customers for reviews, or steering unhappy ones elsewhere first",
          "Holding new reviews for approval before Google shows them on the profile"
        ]
      },
      {
        "question": "What's the best first line of a reply to a negative review?",
        "options": [
          "Explain the business policy that applies to their complaint",
          "Mention the date and details of their visit",
          "Thank them for taking the time to write to you",
          "Offer a free service in exchange for removing the review"
        ]
      },
      {
        "question": "How should AI be used with reviews?",
        "options": [
          "To write sample reviews that show customers what to say",
          "To post replies automatically within minutes, so every reviewer gets a fast response",
          "To draft replies that a person checks and edits before posting",
          "To build customer profiles from reviewers’ names and photos"
        ]
      },
      {
        "question": "When is usually the best moment to ask for a review?",
        "options": [
          "Before the service starts, while they’re most excited about it",
          "About a month later, once they’ve judged the result",
          "Right after the customer got the result they came for",
          "After they’ve visited at least three times and become regulars"
        ]
      }
    ],
    "09": [
      {
        "question": "What's the best way to improve an AI assistant's first answer?",
        "options": [
          "Start a new chat and paste the exact same request again",
          "Switch to a different AI assistant and compare the two answers",
          "Accept it, since the first answer is usually the most accurate",
          "Reply in the same chat saying what to change, like \"shorter\" or \"friendlier\""
        ]
      },
      {
        "question": "Which of these should you NOT paste into an AI assistant?",
        "options": [
          "A message you received, with names removed",
          "A rough list of points you want in an email",
          "An email you wrote that shows your usual style",
          "Your password or a customer's card number"
        ]
      },
      {
        "question": "Which request will get the most useful email draft?",
        "options": [
          "\"Write a professional email about the delivery delay\"",
          "\"Write the best possible customer email\"",
          "The topic in one word, so the AI has room to be creative",
          "Who it's for, what happened, what you want them to do, and the tone"
        ]
      },
      {
        "question": "You need to have a tough conversation with your landlord. How can AI help most?",
        "options": [
          "Find the landlord's private details so you have more leverage",
          "Write a message with stronger claims than what really happened",
          "Call the landlord for you so you avoid the awkward moment",
          "Play the landlord so you can practice, then suggest better wording"
        ]
      },
      {
        "question": "What does it mean when an AI \"hallucinates\"?",
        "options": [
          "It gives a different answer when you ask again",
          "It refuses to help with a request it finds unsafe",
          "It stops answering because the chat got too long",
          "It states something false while sounding sure"
        ]
      }
    ]
  },
  "es": {
    "10": [
      {
        "question": "¿En qué suelen fallar todavía las herramientas de imagen con IA?",
        "options": [
          "Convertir una descripción en una imagen nueva",
          "Escribir bien las palabras dentro de una imagen",
          "Hacer una imagen con estilo de acuarela",
          "Quitar el fondo de la foto de un producto"
        ]
      },
      {
        "question": "Quieres una imagen de la fachada real de tu local para tu web. ¿Qué es lo mejor?",
        "options": [
          "Hacer una foto real y usar la IA para mejorar la luz o el encuadre",
          "Pedir a la IA una versión que parezca más grande de lo que es",
          "Usar una foto de archivo de un local parecido y añadir tu logo",
          "Describir tu local a un generador de imágenes y usar su imagen"
        ]
      },
      {
        "question": "¿Qué parte le falta a esta descripción: \"un golden retriever con gorro de fiesta, estilo dibujo animado, cuadrado\"?",
        "options": [
          "Lugar, luz y ambiente",
          "Formato y tamaño",
          "Estilo",
          "Tema"
        ]
      },
      {
        "question": "¿Qué es un deepfake?",
        "options": [
          "Una ilustración con estilo realista en lugar de dibujo animado",
          "Una foto a la que una herramienta de IA le quitó el fondo",
          "Contenido hecho con IA que muestra a una persona real haciendo o diciendo algo que no hizo",
          "Cualquier imagen editada con un filtro o una corrección de color"
        ]
      },
      {
        "question": "¿Qué uso de imágenes con IA es honesto?",
        "options": [
          "Fotos de clientes hechas con IA junto a reseñas reales",
          "Una imagen de producto con funciones que el producto no tiene",
          "Un fondo claramente ilustrado para el volante de una venta de pasteles",
          "Fotos de \"antes y después\" creadas para mostrar resultados que no has tenido"
        ]
      }
    ],
    "11": [
      {
        "question": "¿Cuál es el primer paso del método de vaciar la cabeza?",
        "options": [
          "Abrir el calendario y reservar tiempo para la tarea más importante",
          "Escribir cada tarea y preocupación en cualquier orden, sin organizarlas",
          "Preguntar a la IA qué tareas deberías dejar esta semana",
          "Ordenar las tareas de más a menos urgente antes de escribirlas"
        ]
      },
      {
        "question": "¿Por qué debes decirle a la IA cuánto tardas de verdad en cada tarea?",
        "options": [
          "Sin tiempos se niega a hacer cualquier plan",
          "Necesita los tiempos para conectarse sola a tu calendario",
          "No lo sabe, y los planes sin ese dato suelen ser poco realistas",
          "Usa los tiempos para decidir qué tareas eliminar por ti"
        ]
      },
      {
        "question": "¿Cuál es una forma segura de pedir ayuda con tu presupuesto?",
        "options": [
          "Darle tu acceso a la banca en línea para que revise los saldos",
          "Pegar tus extractos bancarios completos para que vea cada detalle",
          "Describir ingresos y gastos por categorías aproximadas",
          "Darle los números de tus tarjetas para seguir los gastos"
        ]
      },
      {
        "question": "Usas la IA para entender una duda de salud. ¿Qué es lo correcto?",
        "options": [
          "Seguir su consejo en lugar de ir al médico para ahorrar tiempo",
          "Pedirle un diagnóstico y comprar el medicamento que sugiera",
          "Usarla para entender opciones y preparar preguntas para tu médico",
          "Evitar la IA por completo, porque no puede explicar nada médico"
        ]
      },
      {
        "question": "¿Cuál es la mejor forma de aprender un tema nuevo con IA?",
        "options": [
          "Leer su primera explicación y fiarte sin comprobar",
          "Pedirle que haga tus deberes para estudiar las respuestas",
          "Pedir que lo explique fácil, que te ponga a prueba y comprobar los datos importantes",
          "Pedir la explicación más larga y detallada posible"
        ]
      }
    ],
    "12": [
      {
        "question": "Antes de añadir IA para atender clientes, ¿qué deberías hacer primero?",
        "options": [
          "Elegir el sistema telefónico con IA más avanzado que exista",
          "Quitar tus otras formas de contacto para que todo pase por la IA",
          "Pedir a la IA que adivine qué preguntarán probablemente tus clientes",
          "Hacer una lista de las preguntas reales de los clientes y escribir respuestas claras"
        ]
      },
      {
        "question": "¿Qué mensaje de cliente debe ir siempre a una persona?",
        "options": [
          "\"¿Atienden en mi código postal?\"",
          "\"¿Qué horario tienen el sábado?\"",
          "\"¿Me mandan el enlace para reservar?\"",
          "Un cliente molesto por un trabajo que pide un reembolso"
        ]
      },
      {
        "question": "¿Qué debe hacer un buen asistente de chat con IA cuando no sabe una respuesta?",
        "options": [
          "Responder otra pregunta que sí conoce",
          "Dar su mejor suposición para que el cliente no espere",
          "Cerrar el chat con amabilidad y pedir que lo intenten más tarde",
          "Decir que no está seguro y pasar al cliente con una persona"
        ]
      },
      {
        "question": "¿Por qué es importante decir a los clientes que hablan con una IA?",
        "options": [
          "Permite que la IA se salte las reglas para pasar a una persona",
          "Los clientes prefieren la IA, así que sirve como argumento de venta",
          "Hace que las respuestas de la IA sean más precisas",
          "Genera confianza y en muchos lugares se está volviendo obligatorio"
        ]
      },
      {
        "question": "¿Qué es una base de conocimiento?",
        "options": [
          "La base de datos propia de la empresa de IA sobre internet",
          "Un informe de cuántas llamadas atendió la IA cada semana",
          "La lista de todos los clientes que han chateado con tu negocio",
          "Los datos escritos con los que responde un asistente de IA, como horario, precios y políticas"
        ]
      }
    ],
    "13": [
      {
        "question": "¿Qué debes hacer antes de grabar una reunión para tomar notas con IA?",
        "options": [
          "Nada, mientras la grabación se quede en tu teléfono",
          "Pedir permiso solo si hay un cliente en la llamada",
          "Avisar a todos y conseguir su visto bueno",
          "Grabar a escondidas para que la gente hable con naturalidad"
        ]
      },
      {
        "question": "Un resumen de reunión hecho con IA dice que el cliente aceptó 4.500. ¿Qué haces?",
        "options": [
          "Comprobar la cantidad con lo que recuerdas antes de enviarlo",
          "Borrar el resumen y escribirlo todo desde cero",
          "Enviarlo enseguida, porque las transcripciones siempre aciertan",
          "Redondearlo a 5.000 por si acaso"
        ]
      },
      {
        "question": "¿Cuál es la mejor forma de que la IA redacte una propuesta nueva con tu estilo?",
        "options": [
          "Pegar una propuesta que funcionó y pedirle que la use como plantilla",
          "Pedir la propuesta más larga posible para que no falte nada",
          "Pedir \"una propuesta profesional\" y arreglar el estilo después",
          "Dejar que elija los precios para que la propuesta quede completa"
        ]
      },
      {
        "question": "La IA redactó un contrato para un cliente nuevo. ¿Cuál es el siguiente paso correcto?",
        "options": [
          "Pedir a otra herramienta de IA que confirme que es legal",
          "Que un abogado lo revise antes de que nadie firme",
          "Firmarlo enseguida, porque la IA conoce la ley",
          "Enviarlo tal cual añadiendo \"hecho con IA\" al final"
        ]
      },
      {
        "question": "Una tarea se repite cada día y sigue reglas claras. ¿Dónde aprendes a hacer que funcione sola?",
        "options": [
          "Módulo 02, Herramientas de IA y automatización",
          "Módulo 11, Planifica tu semana y tu día a día",
          "Módulo 10, Crea imágenes y videos",
          "Módulo 08, Reseñas y reputación"
        ]
      }
    ],
    "14": [
      {
        "question": "¿Qué hace que los consejos de negocio de la IA sean mejores?",
        "options": [
          "Hacer la misma pregunta varias veces y quedarte con la respuesta más atrevida",
          "Darle el panorama completo y pedirle que te pregunte primero",
          "Hacer una pregunta de una línea para no influirla",
          "Pedirle que apoye tu plan para mantener la motivación"
        ]
      },
      {
        "question": "La IA te da los precios de un competidor a partir de una búsqueda web. ¿Qué haces?",
        "options": [
          "Abrir las fuentes para comprobar que son correctos y actuales",
          "Suponer que son bajos y sumarles un 10%",
          "Usarlos enseguida, porque la búsqueda web siempre está al día",
          "Ignorarlos, porque la IA nunca puede investigar competidores"
        ]
      },
      {
        "question": "La IA calcula que subir precios te hará ganar más. ¿Cuál es el siguiente paso inteligente?",
        "options": [
          "Comprobar las cuentas tú mismo o en una hoja de cálculo",
          "Pedirle que redondee las cifras para que se vean más limpias",
          "Subir precios mañana, porque la IA es buena con los números",
          "Bajar los precios por si acaso"
        ]
      },
      {
        "question": "¿Cuál es una buena forma de probar una oferta nueva antes de invertir?",
        "options": [
          "Construirla entera y luego anunciarla a todo el mundo",
          "Ofrecerla primero a unos pocos clientes y ver quién dice que sí",
          "Preguntar a la IA si gustará y fiarte de la respuesta",
          "Copiar exactamente la oferta de un competidor, porque ya está probada"
        ]
      },
      {
        "question": "¿Dónde encuentras una razón mejor que una suposición de la IA para elegir una oportunidad?",
        "options": [
          "En conversaciones cortas con clientes reales",
          "En una respuesta de IA más larga y detallada",
          "En la oportunidad que suena más emocionante",
          "En lo que recomiende la herramienta de IA más popular"
        ]
      }
    ],
    "01": [
      {
        "question": "¿Qué es una 'alucinación' en la IA?",
        "options": [
          "Cuando una IA repite palabra por palabra sus datos de entrenamiento en lugar de crear algo nuevo",
          "Cuando una IA confunde instrucciones anteriores de una conversación larga con las nuevas",
          "Cuando una IA da una respuesta distinta cada vez que le haces la misma pregunta",
          "Cuando una IA afirma información falsa con seguridad, como una estadística o fuente inventada"
        ]
      },
      {
        "question": "¿Cuál de estos es un ejemplo de IA predictiva?",
        "options": [
          "Un chatbot que reescribe la descripción de tu producto en un tono más amigable y corto",
          "Un asistente de IA que convierte tus notas de reunión en un correo de seguimiento para un prospecto",
          "Una herramienta de imágenes que crea tres versiones de un anuncio en distintos tamaños",
          "Una plataforma de anuncios que decide qué personas tienen más probabilidades de hacer clic en tu anuncio"
        ]
      },
      {
        "question": "¿Cuál es el mejor punto de partida para usar IA en tu marketing?",
        "options": [
          "Elegir la herramienta de IA más popular y usarla en todo",
          "Pedirle a la IA un mes de publicaciones primero, porque el contenido es lo más rápido",
          "Automatizar las tareas que requieren más clics, empezando por los mensajes de clientes",
          "Encontrar la etapa del embudo donde pierdes más tiempo o clientes"
        ]
      },
      {
        "question": "¿Qué tarea siempre debe tener aprobación humana antes de publicarse?",
        "options": [
          "Un resumen interno de un formulario de prospecto para el vendedor",
          "Etiquetar mensajes como ventas, soporte o spam",
          "Una lista de ideas de temas para el blog del equipo de marketing",
          "Un correo promocional que van a leer tus clientes"
        ]
      },
      {
        "question": "¿Qué uso de la IA NO es aceptable?",
        "options": [
          "Redactar respuestas a preguntas frecuentes para que una persona las revise",
          "Resumir reseñas reales de clientes para encontrar temas comunes",
          "Generar ideas de titulares y asuntos de correo para una promoción",
          "Generar testimonios de clientes realistas para usarlos en tus anuncios"
        ]
      }
    ],
    "02": [
      {
        "question": "En un flujo de automatización, ¿qué es un 'disparador'?",
        "options": [
          "El paso que envía información a un modelo de IA y usa su respuesta",
          "El evento que inicia el flujo, como el envío de un nuevo formulario",
          "La acción que ocurre después de guardar un prospecto, como un correo de confirmación",
          "Una regla que decide si el flujo continúa, como un presupuesto mínimo"
        ]
      },
      {
        "question": "¿Cuál es la mejor forma de hacer predecible un paso de IA en un flujo?",
        "options": [
          "Pedirle a la IA que explique su razonamiento en un párrafo completo antes de cada respuesta",
          "Darle a la IA más libertad creativa para que pueda manejar cualquier respuesta",
          "Exigir un formato de respuesta fijo y agregar un plan alternativo para respuestas inesperadas",
          "Usar el modelo de IA más nuevo, porque los modelos nuevos siempre siguen las instrucciones"
        ]
      },
      {
        "question": "¿Qué debes hacer ANTES de automatizar un proceso?",
        "options": [
          "Elegir la plataforma de automatización con más integraciones de apps",
          "Conectar todas las apps del equipo",
          "Mapear exactamente cómo funciona el proceso hoy, paso a paso",
          "Quitar los pasos de aprobación humana para que el flujo funcione solo"
        ]
      },
      {
        "question": "Al evaluar una nueva herramienta de IA, ¿qué pregunta importa más?",
        "options": [
          "¿Cuántas funciones tiene en comparación con otras herramientas del mercado?",
          "¿Sus ejemplos de demostración se ven mejor que lo que producen nuestras herramientas?",
          "¿Qué tarea específica mejora y puedo medir la diferencia?",
          "¿Es la más nueva del mercado?"
        ]
      },
      {
        "question": "¿Por qué mantener al principio un paso de aprobación humana en los flujos que ve el cliente?",
        "options": [
          "Para hacer más lento el flujo y que los clientes no noten que las respuestas son automáticas",
          "Porque las plataformas de automatización no envían nada a los clientes sin ese paso",
          "Para detectar errores antes de que los vean los clientes mientras confirmas que la IA es confiable",
          "Porque los resultados de la IA nunca deben llegar directamente a los clientes, ni siquiera después de meses de buenos resultados"
        ]
      }
    ],
    "03": [
      {
        "question": "¿Qué prompt probablemente dará el mejor resultado?",
        "options": [
          "Un prompt corto para que la IA complete los detalles con su propia creatividad",
          "\"Escribe una gran publicación sobre nuestro negocio que se haga viral en Instagram.\"",
          "Un prompt con rol, contexto, tarea, formato y restricciones",
          "Un párrafo largo sobre la historia del negocio"
        ]
      },
      {
        "question": "¿Qué son los 'prompts con ejemplos' (few-shot)?",
        "options": [
          "Pedirle a la IA varios borradores cortos y elegir el mejor",
          "Escribir prompts con la menor cantidad de palabras posible para ahorrar en costos de uso",
          "Incluir en el prompt algunos ejemplos de cómo se ve un buen resultado",
          "Dividir una tarea grande en algunos prompts más pequeños que se ejecutan uno tras otro"
        ]
      },
      {
        "question": "La IA te da un borrador débil. ¿Cuál es el mejor siguiente paso?",
        "options": [
          "Hacer clic en regenerar varias veces hasta que aparezca una versión mejor por sí sola",
          "Cambiar a otra herramienta de IA, porque la primera ya demostró que no puede con este tipo de tarea",
          "Identificar qué faltó en el prompt, agregarlo y darle comentarios específicos",
          "Responder \"mejóralo\" para que la IA sepa que debe superar su primer intento"
        ]
      },
      {
        "question": "¿Qué debe incluir una guía de voz de marca?",
        "options": [
          "Una lista de las herramientas de IA que usa el equipo y quién tiene acceso a cada una",
          "Rasgos de voz con ejemplos, palabras que usar y evitar, y reglas claras sobre afirmaciones",
          "Los archivos del logo, los colores de marca y las tipografías aprobadas para cada plataforma",
          "Eslóganes de la competencia para que tus mensajes les resulten familiares a los clientes"
        ]
      },
      {
        "question": "¿Por qué crear una biblioteca de prompts compartida?",
        "options": [
          "Convierte los prompts con mejor resultado de una persona en el estándar del equipo",
          "Reemplaza la necesidad de una estrategia de contenido, porque los prompts definen los temas",
          "Significa que los resultados de prompts guardados ya no necesitan edición humana",
          "La mayoría de las herramientas de IA solo recuerdan prompts guardados en una biblioteca compartida"
        ]
      }
    ],
    "04": [
      {
        "question": "¿Qué debe venir primero al planificar contenido asistido por IA?",
        "options": [
          "El calendario de contenido de un competidor como punto de partida",
          "Qué herramienta de IA y estilo de imagen usar para la marca",
          "El objetivo de negocio y una audiencia específica a alcanzar",
          "Cuántas publicaciones hacer cada día en cada plataforma"
        ]
      },
      {
        "question": "¿Qué son los pilares de contenido?",
        "options": [
          "De tres a cinco temas recurrentes que conectan las necesidades de la audiencia con lo que vendes",
          "Las plataformas donde publicas con más frecuencia, como Instagram y Google",
          "Un conjunto fijo de hashtags de marca que agregas a cada publicación para que sea fácil de encontrar",
          "Las tres a cinco publicaciones con más interacción, reutilizadas como plantillas"
        ]
      },
      {
        "question": "En la pirámide de reutilización, ¿qué necesita más la pieza pilar?",
        "options": [
          "La mayor extensión posible para poder dividirla en más piezas",
          "Experiencia propia, conocimiento o historias reales del negocio",
          "Un formato o audio de tendencia para llegar a personas que no te siguen",
          "La mayor cantidad posible de palabras clave para posicionar en cada búsqueda relacionada"
        ]
      },
      {
        "question": "¿Qué tipo de contenido dice Google que premia?",
        "options": [
          "Páginas largas que usan la palabra clave principal en cada título y párrafo",
          "Contenido útil, confiable y pensado para las personas, sin importar cómo se produjo",
          "Una página distinta para cada ciudad atendida, con el mismo texto y solo el nombre de la ciudad cambiado",
          "Contenido escrito por personas, porque Google baja el posicionamiento de todo lo asistido por IA"
        ]
      },
      {
        "question": "¿Qué paso del flujo de contenido con IA protege más la calidad?",
        "options": [
          "La edición y verificación humana antes de publicar",
          "Programar las publicaciones a la mejor hora del día",
          "Pasar cada borrador por un corrector gramatical con IA",
          "Generar muchas variaciones para elegir"
        ]
      }
    ],
    "05": [
      {
        "question": "¿Cuál es una 'métrica de decisión' y no una métrica de vanidad?",
        "options": [
          "Reproducciones de video",
          "Costo por prospecto",
          "Impresiones totales",
          "Crecimiento de seguidores"
        ]
      },
      {
        "question": "200 personas visitan una página y 10 agendan una llamada. ¿Cuál es la tasa de conversión?",
        "options": [
          "5 %",
          "2 %",
          "10 %",
          "20 %"
        ]
      },
      {
        "question": "Antes de subir una exportación de datos a una herramienta de IA, debes:",
        "options": [
          "Convertirla a PDF para que la IA no pueda cambiar los números originales",
          "Eliminar la información personal, como nombres, correos y teléfonos de clientes",
          "Agregar todas las columnas que tengas para que la IA tenga el mayor contexto posible",
          "Combinar celdas y agregar colores para que la IA entienda mejor la estructura"
        ]
      },
      {
        "question": "Una herramienta de IA reporta un número sorprendente de tus datos. ¿Qué debes hacer?",
        "options": [
          "Compartirlo con el equipo de inmediato para poder tomar decisiones rápido",
          "Pedirle que explique el cálculo y verificar el número tú mismo",
          "Hacer la misma pregunta otra vez",
          "Confiar en él, porque las herramientas de IA calculan con más precisión que una hoja de cálculo"
        ]
      },
      {
        "question": "¿Qué hace que una prueba A/B sea buena?",
        "options": [
          "Cambiar una sola cosa a la vez y esperar suficientes datos",
          "Cambiar todo a la vez para encontrar un ganador más rápido",
          "Probar dos ideas sin anotar qué esperas que pase",
          "Detenerla en cuanto una versión consiga unos cuantos clics más"
        ]
      }
    ],
    "06": [
      {
        "question": "¿Qué significa mantener a una 'persona en el proceso'?",
        "options": [
          "Se pide a los clientes que aprueben las publicaciones escritas por IA antes de publicarlas",
          "Solo una persona del equipo usa herramientas de IA para que los resultados sean consistentes",
          "Una persona escribe cada mensaje y la IA solo se usa para investigación interna",
          "Una persona revisa y aprueba los resultados de IA importantes o que verá el cliente"
        ]
      },
      {
        "question": "¿Cuál es la razón más fuerte para empezar con un flujo pequeño y frecuente?",
        "options": [
          "Un flujo pequeño no necesita pruebas, así que puede activarse el mismo día",
          "Los flujos pequeños son gratis en la mayoría de las plataformas, así que no cuestan nada",
          "Los flujos grandes no pueden incluir pasos de IA hasta que uno pequeño haya funcionado",
          "Ahorra tiempo real con poco riesgo mientras aprendes qué cosas pueden fallar"
        ]
      },
      {
        "question": "¿Qué parte del prompt le dice a la IA qué evitar?",
        "options": [
          "Contexto",
          "Ejemplos",
          "Formato de salida",
          "Restricciones"
        ]
      },
      {
        "question": "¿Qué enfoque tiene más probabilidades de dañar tu visibilidad en buscadores?",
        "options": [
          "Responder con claridad preguntas reales de clientes",
          "Agregar fotos propias de proyectos y descripciones breves a tus páginas de servicios",
          "Mantener los datos del negocio consistentes en toda la web",
          "Publicar cientos de páginas de IA pobres y casi idénticas"
        ]
      },
      {
        "question": "¿Cuál es el mejor uso de la IA para investigar a tu audiencia?",
        "options": [
          "Pegar correos completos de clientes, con nombres y teléfonos, para que la IA lo vea todo",
          "Pedirle a la IA que invente perfiles de clientes detallados, con nombres y profesiones, cuando aún no tienes datos reales",
          "Escribir reseñas de muestra con IA y publicarlas para ver cuáles generan reacciones",
          "Encontrar preguntas comunes y frases exactas en reseñas y mensajes de clientes anónimos"
        ]
      },
      {
        "question": "En comparación con el costo de adquisición (CAC), el valor de vida del cliente (LTV) debe ser:",
        "options": [
          "Menor que el CAC mientras el negocio crece rápido",
          "Más o menos igual al CAC, para que el marketing se pague solo",
          "Sin relación con el CAC, porque miden cosas distintas",
          "Mucho mayor que el CAC, como ocurre en un negocio sano"
        ]
      },
      {
        "question": "¿A qué debe llevar un informe semanal de marketing?",
        "options": [
          "A una lista completa de todas las métricas para no perder nada",
          "A un registro de resultados para revisar a fin de año",
          "A una gráfica de crecimiento de seguidores para el dueño",
          "A decisiones y acciones específicas para la próxima semana"
        ]
      },
      {
        "question": "Un asistente de chat en tu sitio responde preguntas de clientes. ¿Qué exige un uso responsable?",
        "options": [
          "Dejar que ofrezca descuentos por su cuenta para cerrar ventas más rápido",
          "Darle un nombre y una foto de empleado para que los clientes se sientan más cómodos",
          "Dejarlo fuera de la política de privacidad, porque no guarda ningún dato",
          "Dejar claro que es automatizado y ofrecer una forma fácil de hablar con una persona"
        ]
      },
      {
        "question": "¿Qué afirmación sobre las herramientas de IA es verdadera?",
        "options": [
          "Sus resultados solo necesitan edición cuando el prompt estaba mal escrito",
          "Aprenden sobre tu negocio automáticamente después de usarlas unas semanas",
          "Verifican los datos en la web antes de cada respuesta, así que sus afirmaciones son confiables tal como vienen",
          "Producen texto que suena correcto pero puede estar mal, así que hay que verificar las afirmaciones"
        ]
      },
      {
        "question": "¿Para qué sirve una métrica Estrella Polar?",
        "options": [
          "Para reemplazar todas las demás métricas y que el equipo mire un solo número",
          "Para definir la visión de largo plazo que guía el contenido de la marca",
          "Para medir la mayor cantidad posible de números y no perder ninguna parte del embudo",
          "Para enfocar al equipo en el número que mejor representa el éxito actual"
        ]
      }
    ],
    "07": [
      {
        "question": "¿En qué tres cosas dice Google que se basan los resultados locales?",
        "options": [
          "Número de publicaciones, fotos y palabras clave",
          "Relevancia, distancia y prominencia",
          "Precio, horario de atención y fotos",
          "Inversión en anuncios, antigüedad del sitio y número de reseñas"
        ]
      },
      {
        "question": "El nombre del perfil de una barbería es \"Brancato Barbershop Mejores Cortes Boston\". ¿Cuál es el problema?",
        "options": [
          "Agregar palabras clave al nombre va contra las reglas de Google y puede hacer que suspendan el perfil",
          "Los nombres de perfil no pueden incluir una ciudad, así que Boston debe ir en el campo de dirección",
          "El nombre es demasiado largo y Google corta todo lo que va después de las tres primeras palabras",
          "Ninguno: agregar la ciudad y el servicio al nombre lo ayuda a posicionar en esas búsquedas"
        ]
      },
      {
        "question": "¿Qué ajuste es el más importante para la relevancia en un Perfil de Empresa de Google?",
        "options": [
          "La descripción del negocio",
          "La categoría principal",
          "El número de publicaciones",
          "La foto de portada"
        ]
      },
      {
        "question": "¿Qué es una citación en SEO local?",
        "options": [
          "Un enlace de otro sitio web al tuyo, que Google cuenta como un voto de confianza",
          "Una cita o reseña de un cliente que el negocio muestra en su propio sitio web",
          "Cualquier lugar en línea que muestra el nombre, la dirección y el teléfono del negocio",
          "Un aviso de Google cuando un perfil rompe sus reglas sobre nombres o reseñas"
        ]
      },
      {
        "question": "El negocio se mudó el año pasado. Yelp y Facebook todavía muestran la dirección vieja. ¿Por qué arreglarlo?",
        "options": [
          "Las direcciones viejas ayudan a que el negocio aparezca en las búsquedas de dos barrios hasta que se establezca en el nuevo",
          "Solo importa para negocios que pagan anuncios en Google o Facebook",
          "Tener los mismos datos en todas partes ayuda a Google a confiar en cuál es la información correcta",
          "Solo importan los datos de Google, así que los otros sitios no necesitan corrección"
        ]
      }
    ],
    "08": [
      {
        "question": "¿Cuál de estas cosas está permitida al pedir reseñas en Google?",
        "options": [
          "Ofrecer un 10 % de descuento por una reseña de 5 estrellas",
          "Pedírsela a todos los clientes de la misma forma, con un enlace corto",
          "Pedírsela solo a los clientes que dijeron que estaban contentos con la visita",
          "Que los empleados publiquen reseñas desde sus propias cuentas sobre trabajos reales"
        ]
      },
      {
        "question": "¿Qué es filtrar reseñas (review gating)?",
        "options": [
          "Denunciar reseñas que rompen las reglas de Google, como spam o conflictos de interés, para que las eliminen",
          "Responder cada reseña en menos de un día para que los clientes descontentos no publiquen más",
          "Pedir reseñas solo a los clientes contentos, o mandar primero a los descontentos a otro lugar",
          "Retener las reseñas nuevas para aprobarlas antes de que Google las muestre en el perfil"
        ]
      },
      {
        "question": "¿Cuál es la mejor primera frase de una respuesta a una reseña negativa?",
        "options": [
          "Explicar la política del negocio que aplica a su queja",
          "Mencionar la fecha y los detalles de su visita",
          "Agradecerle que se haya tomado el tiempo de escribir",
          "Ofrecer un servicio gratis a cambio de que elimine la reseña"
        ]
      },
      {
        "question": "¿Cómo se debe usar la IA con las reseñas?",
        "options": [
          "Para escribir reseñas de muestra que les enseñen a los clientes qué decir",
          "Para publicar respuestas automáticamente en minutos, así cada cliente recibe una respuesta rápida",
          "Para redactar respuestas que una persona revisa y edita antes de publicarlas",
          "Para crear perfiles de clientes a partir de los nombres y fotos de quienes dejan reseñas"
        ]
      },
      {
        "question": "¿Cuál suele ser el mejor momento para pedir una reseña?",
        "options": [
          "Antes de que empiece el servicio, cuando está más entusiasmado",
          "Un mes después, cuando ya tuvo tiempo de evaluar el resultado",
          "Justo después de que el cliente recibió el resultado que vino a buscar",
          "Después de que haya venido al menos tres veces y sea un cliente habitual"
        ]
      }
    ],
    "09": [
      {
        "question": "¿Cuál es la mejor forma de mejorar la primera respuesta de un asistente de IA?",
        "options": [
          "Abrir un chat nuevo y pegar exactamente el mismo pedido",
          "Cambiar a otro asistente de IA y comparar las dos respuestas",
          "Aceptarla, porque la primera respuesta suele ser la más precisa",
          "Responder en el mismo chat diciendo qué cambiar, como \"más corto\" o \"más amable\""
        ]
      },
      {
        "question": "¿Cuál de estas cosas NO deberías pegar en un asistente de IA?",
        "options": [
          "Un mensaje que recibiste, sin los nombres",
          "Una lista de ideas que quieres en un correo",
          "Un correo tuyo que muestra tu estilo habitual",
          "Tu contraseña o el número de tarjeta de un cliente"
        ]
      },
      {
        "question": "¿Qué pedido dará el borrador de correo más útil?",
        "options": [
          "\"Escribe un correo profesional sobre el retraso del envío\"",
          "\"Escribe el mejor correo posible para un cliente\"",
          "El tema en una palabra, para que la IA tenga espacio para crear",
          "Para quién es, qué pasó, qué quieres que hagan y el tono"
        ]
      },
      {
        "question": "Tienes que tener una conversación difícil con tu casero. ¿Cómo te ayuda más la IA?",
        "options": [
          "Buscando datos privados del casero para tener más poder",
          "Escribiendo un mensaje con quejas más fuertes de lo que pasó",
          "Llamando al casero por ti para evitar el momento incómodo",
          "Haciendo del casero para que practiques y sugiriendo mejores palabras"
        ]
      },
      {
        "question": "¿Qué significa que una IA \"alucine\"?",
        "options": [
          "Da una respuesta distinta cuando vuelves a preguntar",
          "Se niega a ayudar con un pedido que considera inseguro",
          "Deja de responder porque el chat es demasiado largo",
          "Afirma algo falso sonando segura"
        ]
      }
    ]
  },
  "pt": {
    "10": [
      {
        "question": "Em que as ferramentas de imagem com IA ainda costumam errar?",
        "options": [
          "Transformar uma descrição em uma imagem nova",
          "Escrever palavras corretamente dentro de uma imagem",
          "Fazer uma imagem em estilo aquarela",
          "Tirar o fundo da foto de um produto"
        ]
      },
      {
        "question": "Você quer uma imagem da fachada real da sua loja para o site. Qual é a melhor opção?",
        "options": [
          "Tirar uma foto real e usar a IA para melhorar a luz ou o enquadramento",
          "Pedir à IA uma versão que pareça maior do que é",
          "Usar uma foto de banco de imagens de uma loja parecida e pôr seu logo",
          "Descrever sua loja para um gerador de imagens e usar a imagem dele"
        ]
      },
      {
        "question": "Que parte está faltando nesta descrição: \"um golden retriever com chapéu de festa, estilo desenho animado, quadrado\"?",
        "options": [
          "Cenário, luz e clima",
          "Formato e tamanho",
          "Estilo",
          "Assunto"
        ]
      },
      {
        "question": "O que é um deepfake?",
        "options": [
          "Uma ilustração em estilo realista em vez de desenho animado",
          "Uma foto que teve o fundo removido por uma ferramenta de IA",
          "Conteúdo feito com IA mostrando uma pessoa real fazendo ou dizendo algo que não fez",
          "Qualquer imagem editada com filtro ou correção de cor"
        ]
      },
      {
        "question": "Qual uso de imagens com IA é honesto?",
        "options": [
          "Fotos de clientes feitas com IA ao lado de avaliações reais",
          "Uma imagem de produto com recursos que o produto não tem",
          "Um fundo claramente ilustrado para o panfleto de uma venda de bolos",
          "Fotos de \"antes e depois\" criadas para mostrar resultados que você não teve"
        ]
      }
    ],
    "11": [
      {
        "question": "Qual é o primeiro passo do método de esvaziar a cabeça?",
        "options": [
          "Abrir a agenda e reservar tempo para a tarefa mais importante",
          "Escrever cada tarefa e preocupação em qualquer ordem, sem organizar",
          "Perguntar à IA quais tarefas você deve largar nesta semana",
          "Ordenar as tarefas da mais à menos urgente antes de digitar"
        ]
      },
      {
        "question": "Por que você deve dizer à IA quanto tempo as tarefas realmente levam?",
        "options": [
          "Sem os tempos ela se recusa a fazer qualquer plano",
          "Ela precisa dos tempos para se conectar sozinha à sua agenda",
          "Ela não sabe, e planos sem essa informação costumam ser irreais",
          "Ela usa os tempos para decidir quais tarefas eliminar por você"
        ]
      },
      {
        "question": "Qual é uma forma segura de pedir ajuda com seu orçamento?",
        "options": [
          "Passar seu login do banco para ela conferir os saldos",
          "Colar seus extratos bancários completos para ela ver cada detalhe",
          "Descrever renda e gastos em categorias aproximadas",
          "Informar os números dos seus cartões para acompanhar os gastos"
        ]
      },
      {
        "question": "Você está usando a IA para entender uma dúvida de saúde. Qual é a abordagem certa?",
        "options": [
          "Seguir o conselho dela em vez de ir ao médico para ganhar tempo",
          "Pedir um diagnóstico e comprar o remédio que ela sugerir",
          "Usar para entender as opções e preparar perguntas para o médico",
          "Evitar a IA totalmente, porque ela não explica nada de saúde"
        ]
      },
      {
        "question": "Qual é a melhor forma de aprender um assunto novo com IA?",
        "options": [
          "Ler a primeira explicação e confiar sem conferir",
          "Pedir que ela faça sua lição de casa para você estudar as respostas",
          "Pedir que explique de forma simples, que teste você e conferir os fatos importantes",
          "Pedir a explicação mais longa e detalhada possível"
        ]
      }
    ],
    "12": [
      {
        "question": "Antes de colocar IA para atender clientes, o que fazer primeiro?",
        "options": [
          "Escolher o sistema telefônico com IA mais avançado que existir",
          "Desligar seus outros canais para que tudo passe pela IA",
          "Pedir para a IA adivinhar o que seus clientes provavelmente vão perguntar",
          "Listar as perguntas que os clientes realmente fazem e escrever respostas claras"
        ]
      },
      {
        "question": "Qual mensagem de cliente deve sempre ir para uma pessoa?",
        "options": [
          "\"Vocês atendem no meu CEP?\"",
          "\"Qual o horário de vocês no sábado?\"",
          "\"Pode me mandar o link para agendar?\"",
          "Um cliente irritado com um serviço pedindo reembolso"
        ]
      },
      {
        "question": "O que um bom assistente de chat com IA deve fazer quando não sabe uma resposta?",
        "options": [
          "Responder outra pergunta que ele sabe",
          "Dar o melhor palpite para o cliente não ficar esperando",
          "Encerrar a conversa com educação e pedir para tentarem mais tarde",
          "Dizer que não tem certeza e passar o cliente para uma pessoa"
        ]
      },
      {
        "question": "Por que é importante avisar os clientes que estão falando com uma IA?",
        "options": [
          "Permite que a IA pule as regras de passagem para uma pessoa",
          "Os clientes preferem IA, então funciona como argumento de venda",
          "Deixa as respostas da IA mais precisas",
          "Gera confiança e, em muitos lugares, está virando exigência legal"
        ]
      },
      {
        "question": "O que é uma base de conhecimento?",
        "options": [
          "O banco de dados próprio da empresa de IA sobre a internet",
          "Um relatório de quantas ligações a IA atendeu por semana",
          "A lista de todos os clientes que já conversaram com seu negócio",
          "Os fatos escritos com que um assistente de IA responde, como horário, preços e políticas"
        ]
      }
    ],
    "13": [
      {
        "question": "O que você deve fazer antes de gravar uma reunião para anotações com IA?",
        "options": [
          "Nada, desde que a gravação fique no seu celular",
          "Pedir permissão só se houver um cliente na ligação",
          "Avisar todo mundo e pedir autorização",
          "Gravar escondido para as pessoas falarem naturalmente"
        ]
      },
      {
        "question": "Um resumo de reunião feito com IA diz que o cliente aceitou 4.500. O que fazer?",
        "options": [
          "Conferir o valor com o que você lembra antes de enviar",
          "Apagar o resumo e escrever tudo do zero",
          "Enviar na hora, porque transcrições sempre acertam",
          "Arredondar para 5.000 por segurança"
        ]
      },
      {
        "question": "Qual é a melhor forma de a IA rascunhar uma proposta nova no seu estilo?",
        "options": [
          "Colar uma proposta que funcionou e pedir para usar como modelo",
          "Pedir a proposta mais longa possível para não faltar nada",
          "Pedir \"uma proposta profissional\" e ajustar o estilo depois",
          "Deixar ela escolher os preços para a proposta ficar completa"
        ]
      },
      {
        "question": "A IA rascunhou um contrato para um cliente novo. Qual é o próximo passo certo?",
        "options": [
          "Pedir a outra ferramenta de IA para confirmar que é legal",
          "Um advogado revisar antes de alguém assinar",
          "Assinar na hora, porque a IA conhece a lei",
          "Enviar como está, colocando \"feito com IA\" no final"
        ]
      },
      {
        "question": "Uma tarefa se repete todo dia e segue regras claras. Onde você aprende a fazê-la rodar sozinha?",
        "options": [
          "Módulo 02, Ferramentas de IA e Automação",
          "Módulo 11, Planeje a semana e o dia a dia",
          "Módulo 10, Crie imagens e vídeos",
          "Módulo 08, Avaliações e Reputação"
        ]
      }
    ],
    "14": [
      {
        "question": "O que torna melhores os conselhos de negócio da IA?",
        "options": [
          "Fazer a mesma pergunta várias vezes e ficar com a resposta mais ousada",
          "Dar o quadro completo e pedir que ela pergunte primeiro",
          "Fazer uma pergunta de uma linha para não influenciá-la",
          "Pedir que ela apoie seu plano para você manter a motivação"
        ]
      },
      {
        "question": "A IA traz os preços de um concorrente a partir de uma busca na web. O que fazer?",
        "options": [
          "Abrir as fontes para conferir se estão corretos e atuais",
          "Supor que estão baixos e somar 10%",
          "Usar na hora, porque a busca na web está sempre atualizada",
          "Ignorar, porque a IA nunca consegue pesquisar concorrentes"
        ]
      },
      {
        "question": "A IA calcula que aumentar os preços vai render mais. Qual é o próximo passo inteligente?",
        "options": [
          "Conferir a conta você mesmo ou em uma planilha",
          "Pedir para ela arredondar os valores para ficarem mais bonitos",
          "Aumentar os preços amanhã, porque a IA é boa com números",
          "Baixar os preços por segurança"
        ]
      },
      {
        "question": "Qual é uma boa forma de testar uma oferta nova antes de investir?",
        "options": [
          "Construir tudo e depois anunciar para todo mundo",
          "Oferecer primeiro para alguns clientes e ver quem diz sim",
          "Perguntar à IA se os clientes vão gostar e confiar na resposta",
          "Copiar exatamente a oferta de um concorrente, porque já está provada"
        ]
      },
      {
        "question": "Onde você encontra um motivo melhor que um palpite da IA para escolher uma oportunidade?",
        "options": [
          "Em conversas curtas com clientes reais",
          "Em uma resposta de IA mais longa e detalhada",
          "Na oportunidade que parece mais empolgante",
          "No que a ferramenta de IA mais popular recomendar"
        ]
      }
    ],
    "01": [
      {
        "question": "O que é uma 'alucinação' na IA?",
        "options": [
          "Quando uma IA repete palavra por palavra seus dados de treinamento em vez de criar algo novo",
          "Quando uma IA confunde instruções do início de uma conversa longa com as novas",
          "Quando uma IA dá uma resposta diferente cada vez que você faz a mesma pergunta",
          "Quando uma IA afirma informações falsas com confiança, como uma estatística ou fonte inventada"
        ]
      },
      {
        "question": "Qual destes é um exemplo de IA preditiva?",
        "options": [
          "Um chatbot reescrevendo a descrição do seu produto em um tom mais simpático e curto",
          "Um assistente de IA transformando suas anotações de reunião em um e-mail de follow-up para um lead",
          "Uma ferramenta de imagem criando três versões de um anúncio em tamanhos diferentes",
          "Uma plataforma de anúncios decidindo quais pessoas têm mais chance de clicar no seu anúncio"
        ]
      },
      {
        "question": "Qual é o melhor ponto de partida para usar IA no seu marketing?",
        "options": [
          "Escolher a ferramenta de IA mais popular e usar em tudo",
          "Pedir à IA um mês de posts primeiro, porque conteúdo é o ganho mais rápido",
          "Automatizar as tarefas que exigem mais cliques, começando pelas mensagens de clientes",
          "Encontrar a etapa do funil em que você mais perde tempo ou clientes"
        ]
      },
      {
        "question": "Qual tarefa deve sempre ter aprovação humana antes de ir ao ar?",
        "options": [
          "Um resumo interno de um formulário de lead para o vendedor",
          "Marcar mensagens recebidas como vendas, suporte ou spam",
          "Uma lista de ideias de temas para o blog da equipe de marketing",
          "Um e-mail promocional que os seus clientes vão receber e ler"
        ]
      },
      {
        "question": "Qual uso da IA NÃO é aceitável?",
        "options": [
          "Rascunhar respostas a perguntas frequentes para uma pessoa revisar",
          "Resumir avaliações reais de clientes para encontrar temas em comum",
          "Gerar ideias de títulos para uma promoção",
          "Gerar depoimentos de clientes para seus anúncios"
        ]
      }
    ],
    "02": [
      {
        "question": "Em um fluxo de automação, o que é um 'gatilho'?",
        "options": [
          "A etapa que envia informações para um modelo de IA e usa a resposta dele",
          "O evento que inicia o fluxo, como o envio de um novo formulário no site",
          "A ação que acontece depois que um lead é salvo, como um e-mail de confirmação",
          "Uma regra que decide se o fluxo continua, como um orçamento mínimo"
        ]
      },
      {
        "question": "Qual é a melhor forma de tornar previsível uma etapa de IA em um fluxo?",
        "options": [
          "Pedir que a IA explique seu raciocínio em um parágrafo completo antes de cada resposta",
          "Dar mais liberdade criativa à IA para que ela lide com qualquer resposta",
          "Exigir um formato de resposta fixo e adicionar um plano B para respostas inesperadas",
          "Usar o modelo de IA mais novo, porque modelos novos sempre seguem as instruções"
        ]
      },
      {
        "question": "O que você deve fazer ANTES de automatizar um processo?",
        "options": [
          "Escolher a plataforma de automação com mais integrações de apps",
          "Conectar todos os apps da equipe",
          "Mapear exatamente como o processo funciona hoje, passo a passo",
          "Remover as etapas de aprovação humana para o fluxo rodar sozinho"
        ]
      },
      {
        "question": "Ao avaliar uma nova ferramenta de IA, qual pergunta importa mais?",
        "options": [
          "Quantos recursos ela tem em comparação com outras ferramentas do mercado?",
          "Os exemplos da demonstração parecem melhores do que o que nossas ferramentas produzem?",
          "Qual tarefa específica ela melhora e consigo medir a diferença?",
          "É a mais nova do mercado?"
        ]
      },
      {
        "question": "Por que manter no início uma etapa de aprovação humana nos fluxos que o cliente vê?",
        "options": [
          "Para deixar o fluxo mais lento e os clientes não perceberem que as respostas são automáticas",
          "Porque as plataformas de automação não enviam nada aos clientes sem essa etapa",
          "Para pegar erros antes que os clientes vejam enquanto você confirma que a IA é confiável",
          "Porque os resultados da IA nunca devem chegar direto aos clientes, nem depois de meses de bons resultados"
        ]
      }
    ],
    "03": [
      {
        "question": "Qual prompt provavelmente terá o melhor resultado?",
        "options": [
          "Um prompt curto para a IA completar os detalhes com a própria criatividade",
          "\"Escreva um ótimo post sobre nosso negócio que viralize no Instagram.\"",
          "Um prompt com papel, contexto, tarefa, formato e restrições",
          "Um parágrafo longo sobre a história do negócio"
        ]
      },
      {
        "question": "O que são 'prompts com exemplos' (few-shot)?",
        "options": [
          "Pedir à IA vários rascunhos curtos e escolher o melhor",
          "Escrever prompts com o mínimo de palavras possível para economizar no uso",
          "Incluir no prompt alguns exemplos de como é um bom resultado",
          "Dividir uma tarefa grande em alguns prompts menores que rodam um depois do outro"
        ]
      },
      {
        "question": "A IA entrega um rascunho fraco. Qual é o melhor próximo passo?",
        "options": [
          "Clicar em gerar novamente várias vezes até aparecer uma versão melhor sozinha",
          "Trocar de ferramenta de IA, porque a primeira já mostrou que não dá conta desse tipo de tarefa",
          "Identificar o que faltou no prompt, acrescentar e dar à IA um feedback específico",
          "Responder \"melhore isso\" para a IA saber que precisa superar a primeira tentativa"
        ]
      },
      {
        "question": "O que deve ter em um guia de voz da marca?",
        "options": [
          "Uma lista das ferramentas de IA que a equipe usa e quem tem acesso a cada uma",
          "Traços de voz com exemplos, palavras para usar e evitar e regras sobre afirmações",
          "Os arquivos do logo, as cores da marca e as fontes aprovadas para cada plataforma",
          "Slogans da concorrência para suas mensagens parecerem familiares aos clientes"
        ]
      },
      {
        "question": "Por que criar uma biblioteca de prompts compartilhada?",
        "options": [
          "Ela transforma os prompts de melhor resultado de uma pessoa no padrão de toda a equipe",
          "Ela substitui a necessidade de uma estratégia de conteúdo, porque os prompts definem os temas",
          "Significa que os resultados de prompts salvos não precisam mais de edição humana",
          "A maioria das ferramentas de IA só lembra de prompts salvos em uma biblioteca compartilhada"
        ]
      }
    ],
    "04": [
      {
        "question": "O que deve vir primeiro ao planejar conteúdo com ajuda de IA?",
        "options": [
          "O calendário de conteúdo de um concorrente como ponto de partida",
          "Qual ferramenta de IA e estilo de imagem usar para a marca",
          "O objetivo de negócio e um público específico a alcançar",
          "Quantos posts publicar por dia em cada plataforma"
        ]
      },
      {
        "question": "O que são pilares de conteúdo?",
        "options": [
          "De três a cinco temas recorrentes que conectam as necessidades do público ao que você vende",
          "As plataformas onde você publica com mais frequência, como Instagram e Google",
          "Um conjunto fixo de hashtags da marca adicionado a todo post para facilitar a busca",
          "Os três a cinco posts com mais engajamento, reaproveitados como modelos"
        ]
      },
      {
        "question": "Na pirâmide de reaproveitamento, do que a peça pilar mais precisa?",
        "options": [
          "O maior número possível de palavras para poder dividi-la em mais peças",
          "Experiência própria, conhecimento ou histórias reais vividas pelo negócio",
          "Um formato ou áudio em alta para alcançar pessoas além dos seus seguidores",
          "O máximo possível de palavras-chave para ranquear em toda busca relacionada"
        ]
      },
      {
        "question": "Que tipo de conteúdo o Google diz que valoriza?",
        "options": [
          "Páginas longas que usam a palavra-chave principal em todo título e parágrafo",
          "Conteúdo útil, confiável e feito para as pessoas, não importa como foi produzido",
          "Uma página separada para cada cidade atendida, com o mesmo texto e só o nome da cidade trocado",
          "Conteúdo escrito por pessoas, porque o Google rebaixa tudo o que teve ajuda de IA"
        ]
      },
      {
        "question": "Qual etapa do fluxo de conteúdo com IA mais protege a qualidade?",
        "options": [
          "A edição e a checagem humanas antes de publicar",
          "Agendar os posts para o melhor horário do dia",
          "Passar cada rascunho por um corretor gramatical com IA",
          "Gerar muitas variações para escolher"
        ]
      }
    ],
    "05": [
      {
        "question": "Qual é uma 'métrica de decisão', e não uma métrica de vaidade?",
        "options": [
          "Visualizações de vídeo",
          "Custo por lead",
          "Impressões",
          "Crescimento de seguidores"
        ]
      },
      {
        "question": "200 pessoas visitam uma página e 10 agendam uma ligação. Qual é a taxa de conversão?",
        "options": [
          "5%",
          "2%",
          "10%",
          "20%"
        ]
      },
      {
        "question": "Antes de enviar uma exportação de dados para uma ferramenta de IA, você deve:",
        "options": [
          "Converter para PDF para a IA não conseguir alterar os números originais",
          "Remover informações pessoais, como nomes, e-mails e telefones de clientes",
          "Adicionar todas as colunas que você tiver para a IA ter o máximo de contexto",
          "Mesclar células e adicionar cores para a IA entender melhor a estrutura"
        ]
      },
      {
        "question": "Uma ferramenta de IA aponta um número surpreendente nos seus dados. O que você deve fazer?",
        "options": [
          "Compartilhar com a equipe na hora para as decisões serem tomadas rápido",
          "Pedir que ela explique o cálculo e conferir você mesmo o número nos dados",
          "Fazer a mesma pergunta de novo e usar o número se ele se repetir",
          "Confiar nele, porque ferramentas de IA calculam com mais precisão que planilhas"
        ]
      },
      {
        "question": "O que faz um bom teste A/B?",
        "options": [
          "Mudar uma coisa de cada vez e esperar dados suficientes",
          "Mudar tudo de uma vez para achar um vencedor mais rápido",
          "Testar duas ideias sem anotar o que você espera que aconteça",
          "Parar assim que uma versão tiver alguns cliques a mais"
        ]
      }
    ],
    "06": [
      {
        "question": "O que significa manter uma 'pessoa no processo'?",
        "options": [
          "Os clientes precisam aprovar os posts escritos pela IA antes da publicação",
          "Só uma pessoa da equipe usa ferramentas de IA, para os resultados serem consistentes",
          "Uma pessoa digita cada mensagem, e a IA só é usada para pesquisa interna",
          "Uma pessoa revisa e aprova resultados de IA importantes ou que o cliente vai ver"
        ]
      },
      {
        "question": "Qual é o motivo mais forte para começar com um fluxo pequeno e frequente?",
        "options": [
          "Um fluxo pequeno não precisa de testes, então pode entrar no ar no mesmo dia",
          "Fluxos pequenos são gratuitos na maioria das plataformas, então não têm custo",
          "Fluxos grandes não podem ter etapas de IA até um pequeno ter rodado antes",
          "Ele economiza tempo real com baixo risco enquanto você aprende o que pode dar errado"
        ]
      },
      {
        "question": "Qual parte do prompt diz à IA o que evitar?",
        "options": [
          "Contexto",
          "Exemplos",
          "Formato de saída",
          "Restrições"
        ]
      },
      {
        "question": "Qual abordagem tem mais chance de prejudicar sua visibilidade na busca?",
        "options": [
          "Responder com clareza a perguntas reais de clientes",
          "Adicionar fotos próprias de projetos e legendas curtas às suas páginas de serviços",
          "Manter os dados do negócio consistentes em toda a web",
          "Publicar centenas de páginas de IA rasas e quase idênticas"
        ]
      },
      {
        "question": "Qual é o melhor uso da IA para pesquisar seu público?",
        "options": [
          "Colar e-mails completos de clientes, com nomes e telefones, para a IA ver tudo",
          "Pedir à IA que invente perfis detalhados de clientes, com nomes e profissões, quando você ainda não tem dados reais",
          "Escrever avaliações de exemplo com IA e publicá-las para ver quais geram reação",
          "Encontrar perguntas comuns e frases exatas em avaliações e mensagens de clientes anônimas"
        ]
      },
      {
        "question": "Em comparação com o custo de aquisição (CAC), o valor do tempo de vida do cliente (LTV) deve ser:",
        "options": [
          "Menor que o CAC",
          "Mais ou menos igual ao CAC, para o marketing se pagar",
          "Sem relação com o CAC, porque medem coisas diferentes",
          "Muito maior que o CAC em um negócio saudável"
        ]
      },
      {
        "question": "A que um relatório semanal de marketing deve levar?",
        "options": [
          "A uma lista completa de todas as métricas para nada ficar de fora",
          "A um registro de resultados para consultar no fim do ano",
          "A um gráfico de crescimento de seguidores para o dono",
          "A decisões e ações específicas para a próxima semana de trabalho"
        ]
      },
      {
        "question": "Um assistente de chat no seu site responde a perguntas de clientes. O que o uso responsável exige?",
        "options": [
          "Deixar que ele ofereça descontos por conta própria para fechar vendas mais rápido",
          "Dar a ele um nome e uma foto de funcionário para os clientes se sentirem mais à vontade",
          "Deixá-lo fora da política de privacidade, porque ele não guarda nenhum dado",
          "Deixar claro que é automatizado e oferecer um jeito fácil de falar com uma pessoa"
        ]
      },
      {
        "question": "Qual afirmação sobre ferramentas de IA é verdadeira?",
        "options": [
          "Os resultados só precisam de edição quando o prompt foi mal escrito",
          "Elas aprendem sobre o seu negócio automaticamente depois de algumas semanas de uso",
          "Elas checam os fatos na web antes de cada resposta, então as afirmações podem ser usadas como vieram",
          "Elas produzem textos que parecem certos, mas podem estar errados, então as afirmações precisam ser checadas"
        ]
      },
      {
        "question": "Para que serve uma métrica Estrela do Norte?",
        "options": [
          "Para substituir todas as outras métricas e a equipe olhar um único número",
          "Para definir a visão de longo prazo que guia o conteúdo da marca",
          "Para acompanhar o máximo de números possível e não perder nenhuma parte do funil",
          "Para focar a equipe no número que melhor representa o sucesso atual"
        ]
      }
    ],
    "07": [
      {
        "question": "Em quais três coisas o Google diz que os resultados locais se baseiam?",
        "options": [
          "Número de posts, fotos e palavras-chave",
          "Relevância, distância e destaque",
          "Preço, horário de funcionamento e fotos",
          "Investimento em anúncios, idade do site e número de avaliações"
        ]
      },
      {
        "question": "O nome do perfil de uma barbearia é \"Brancato Barbershop Melhores Cortes Boston\". Qual é o problema?",
        "options": [
          "Colocar palavras-chave no nome vai contra as regras do Google e pode fazer o perfil ser suspenso",
          "Nomes de perfil não podem ter cidade, então Boston precisa ir para o campo de endereço",
          "O nome é longo demais, e o Google corta tudo depois das três primeiras palavras",
          "Nenhum: colocar a cidade e o serviço no nome ajuda a ranquear nessas buscas"
        ]
      },
      {
        "question": "Qual configuração é a mais importante para a relevância em um Perfil da Empresa no Google?",
        "options": [
          "A descrição do negócio",
          "A categoria principal",
          "O número de posts",
          "A foto de capa"
        ]
      },
      {
        "question": "O que é uma citação em SEO local?",
        "options": [
          "Um link de outro site para o seu, que o Google conta como um voto de confiança",
          "Uma frase ou avaliação de cliente que o negócio mostra no próprio site",
          "Qualquer lugar on-line que mostra o nome, o endereço e o telefone do negócio",
          "Um aviso do Google quando um perfil quebra as regras sobre nomes ou avaliações"
        ]
      },
      {
        "question": "O negócio mudou de endereço no ano passado. Yelp e Facebook ainda mostram o endereço antigo. Por que corrigir?",
        "options": [
          "Endereços antigos ajudam o negócio a aparecer nas buscas de dois bairros até se firmar no novo",
          "Só importa para negócios que fazem anúncios no Google ou no Facebook",
          "Dados iguais em todo lugar ajudam o Google a confiar em qual informação está certa",
          "Só os dados do próprio Google importam, então os outros sites não precisam de correção"
        ]
      }
    ],
    "08": [
      {
        "question": "Qual destas coisas é permitida ao pedir avaliações no Google?",
        "options": [
          "Dar 10% de desconto por uma avaliação 5 estrelas",
          "Pedir a todos os clientes do mesmo jeito, com um link curto",
          "Pedir só aos clientes que disseram ter gostado do atendimento",
          "Funcionários publicarem avaliações das próprias contas sobre trabalhos reais"
        ]
      },
      {
        "question": "O que é filtrar avaliações (review gating)?",
        "options": [
          "Denunciar avaliações que quebram as regras do Google, como spam ou conflito de interesse, para serem removidas",
          "Responder a toda avaliação em até um dia para clientes insatisfeitos não publicarem mais",
          "Pedir avaliação só aos clientes satisfeitos, ou mandar os insatisfeitos primeiro para outro lugar",
          "Segurar as avaliações novas para aprovação antes de o Google mostrá-las no perfil"
        ]
      },
      {
        "question": "Qual é a melhor primeira frase de uma resposta a uma avaliação negativa?",
        "options": [
          "Explicar a política do negócio que se aplica à reclamação",
          "Mencionar a data e os detalhes da visita",
          "Agradecer por ter tirado um tempo para escrever",
          "Oferecer um serviço grátis em troca de remover a avaliação"
        ]
      },
      {
        "question": "Como a IA deve ser usada com avaliações?",
        "options": [
          "Para escrever avaliações de exemplo que mostrem aos clientes o que dizer",
          "Para publicar respostas automaticamente em minutos, assim todo cliente recebe resposta rápida",
          "Para escrever respostas que uma pessoa confere e edita antes de serem publicadas",
          "Para montar perfis de clientes a partir dos nomes e fotos de quem avaliou"
        ]
      },
      {
        "question": "Qual costuma ser a melhor hora para pedir uma avaliação?",
        "options": [
          "Antes de o serviço começar, quando ele está mais animado",
          "Um mês depois, quando ele já teve tempo de avaliar o resultado",
          "Logo depois que o cliente recebeu o resultado que veio buscar",
          "Depois que ele vier pelo menos três vezes e virar cliente fiel"
        ]
      }
    ],
    "09": [
      {
        "question": "Qual é a melhor forma de melhorar a primeira resposta de um assistente de IA?",
        "options": [
          "Abrir uma conversa nova e colar exatamente o mesmo pedido",
          "Trocar de assistente de IA e comparar as duas respostas",
          "Aceitar, porque a primeira resposta costuma ser a mais precisa",
          "Responder na mesma conversa dizendo o que mudar, como \"mais curto\" ou \"mais simpático\""
        ]
      },
      {
        "question": "Qual destas coisas você NÃO deve colar em um assistente de IA?",
        "options": [
          "Uma mensagem que você recebeu, sem os nomes",
          "Uma lista de tópicos que você quer em um e-mail",
          "Um e-mail seu que mostra seu estilo de sempre",
          "Sua senha ou o número do cartão de um cliente"
        ]
      },
      {
        "question": "Qual pedido vai gerar o rascunho de e-mail mais útil?",
        "options": [
          "\"Escreva um e-mail profissional sobre o atraso na entrega\"",
          "\"Escreva o melhor e-mail possível para um cliente\"",
          "O assunto em uma palavra, para a IA ter espaço para criar",
          "Para quem é, o que aconteceu, o que você quer que a pessoa faça e o tom"
        ]
      },
      {
        "question": "Você precisa ter uma conversa difícil com seu locador. Como a IA ajuda mais?",
        "options": [
          "Procurando dados privados do locador para você ter mais poder",
          "Escrevendo uma mensagem com reclamações maiores do que o que aconteceu",
          "Ligando para o locador por você para evitar o momento chato",
          "Fazendo o papel do locador para você treinar e sugerindo palavras melhores"
        ]
      },
      {
        "question": "O que significa uma IA \"alucinar\"?",
        "options": [
          "Dar uma resposta diferente quando você pergunta de novo",
          "Recusar ajuda em um pedido que considera inseguro",
          "Parar de responder porque a conversa ficou longa demais",
          "Afirmar algo falso parecendo ter certeza"
        ]
      }
    ]
  }
};

export function getQuiz(number: string, locale: string): QuizQuestion[] | undefined {
  return (quizzes[locale] ?? quizzes.en)[number] ?? quizzes.en[number];
}
