// GENERATED by scripts/build-academy-quizzes.mjs — edit supabase/quiz-source.private.json instead.
// Correct answers are intentionally absent; grading happens in the submit_quiz() database function.

export type QuizQuestion = { question: string; options: string[] };

export const PASS_PERCENT = 80;

export const quizzes: Record<string, QuizQuestion[]> = {
  "01": [
    {
      "question": "What is a 'hallucination' in AI?",
      "options": [
        "When an AI refuses to answer a question",
        "When an AI produces an image instead of text",
        "When an AI states false information confidently, such as a fake statistic or source",
        "When an AI runs too slowly"
      ]
    },
    {
      "question": "Which of these is an example of predictive AI?",
      "options": [
        "Rewriting a blog post for LinkedIn",
        "Writing an email draft from bullet points",
        "An ad platform deciding which people are most likely to click your ad",
        "Creating a social media graphic"
      ]
    },
    {
      "question": "What's the best starting point for using AI in your marketing?",
      "options": [
        "Automate everything at once",
        "Sign up for as many AI tools as possible",
        "Replace your sales team with a chatbot",
        "Find the funnel stage where you're losing the most time or customers"
      ]
    },
    {
      "question": "Which task should always have human approval before going live?",
      "options": [
        "A promotional email that customers will read",
        "An internal summary of a lead form",
        "Tagging incoming messages by topic",
        "A first draft of blog post ideas"
      ]
    },
    {
      "question": "Which use of AI is NOT acceptable?",
      "options": [
        "Generating customer testimonials for your ads",
        "Brainstorming headline ideas",
        "Drafting replies to common customer questions for review",
        "Summarizing real customer reviews to find common themes"
      ]
    }
  ],
  "02": [
    {
      "question": "In an automation workflow, what is a 'trigger'?",
      "options": [
        "An error message when a step fails",
        "The monthly cost of the automation platform",
        "The final email sent to the customer",
        "The event that starts the workflow, like a new form submission"
      ]
    },
    {
      "question": "What's the best way to make an AI step in a workflow predictable?",
      "options": [
        "Run the workflow only once a month",
        "Let the AI write as much as it wants",
        "Require a fixed output format and add a fallback for unexpected replies",
        "Remove all instructions so the AI can be creative"
      ]
    },
    {
      "question": "What should you do BEFORE automating a process?",
      "options": [
        "Connect every app you own",
        "Map exactly how the process works today, step by step",
        "Remove every human approval step",
        "Buy the most expensive automation plan"
      ]
    },
    {
      "question": "When evaluating a new AI tool, which question matters most?",
      "options": [
        "Does it have the most features?",
        "Are other businesses talking about it?",
        "Is it the newest tool on the market?",
        "Which specific task does it improve, and can I measure the difference?"
      ]
    },
    {
      "question": "Why keep a human approval step in customer-facing workflows at first?",
      "options": [
        "Because AI can't write emails",
        "To catch mistakes before customers see them while you confirm the AI output is reliable",
        "Because automation platforms require it",
        "To make the workflow slower on purpose"
      ]
    }
  ],
  "03": [
    {
      "question": "Which prompt will most likely get the best result?",
      "options": [
        "A single keyword",
        "\"Make it viral.\"",
        "A prompt with role, context, task, format and constraints",
        "\"Write something good about our business.\""
      ]
    },
    {
      "question": "What is 'few-shot prompting'?",
      "options": [
        "Writing prompts with as few words as possible",
        "Using the AI for short tasks only",
        "Including a few examples of what good output looks like",
        "Asking the AI only a few questions per day"
      ]
    },
    {
      "question": "The AI gives you a weak draft. What's the best next step?",
      "options": [
        "Tell it to \"make it better\"",
        "Hit regenerate until something better appears",
        "Give up and write it yourself every time",
        "Identify what was missing from the prompt, add it and give specific feedback"
      ]
    },
    {
      "question": "What belongs in a brand voice guide?",
      "options": [
        "Your competitors' pricing",
        "A list of every AI tool on the market",
        "Your company's login passwords",
        "Voice traits with examples, words to use and avoid, and rules on claims"
      ]
    },
    {
      "question": "Why build a shared prompt library?",
      "options": [
        "It turns one person's best-performing prompts into the team's standard",
        "It replaces the need for a content strategy",
        "It lets you avoid ever editing AI output",
        "It's required by AI companies"
      ]
    }
  ],
  "04": [
    {
      "question": "What should come first when planning AI-assisted content?",
      "options": [
        "The business goal and a specific target audience",
        "Picking an AI image style",
        "Choosing how many posts to publish each day",
        "Copying a competitor's content calendar"
      ]
    },
    {
      "question": "What are content pillars?",
      "options": [
        "A list of hashtags",
        "The most expensive posts you publish",
        "Three to five recurring themes that connect audience needs with what you sell",
        "Posts that are pinned to the top of your profile"
      ]
    },
    {
      "question": "In the repurposing pyramid, what does the pillar piece need most?",
      "options": [
        "Real expertise, experience or stories from the business",
        "The highest word count possible",
        "As many keywords as possible",
        "A trending audio track"
      ]
    },
    {
      "question": "What kind of content does Google say it rewards?",
      "options": [
        "Any content written entirely by AI",
        "Hundreds of near-identical pages for every city",
        "Helpful, reliable, people-first content, however it was produced",
        "Pages stuffed with keywords"
      ]
    },
    {
      "question": "Which step in the AI content workflow protects quality the most?",
      "options": [
        "Generating more variations",
        "Scheduling posts at the perfect time",
        "Adding more hashtags",
        "The human edit and fact-check"
      ]
    }
  ],
  "05": [
    {
      "question": "Which is a 'decision metric' rather than a vanity metric?",
      "options": [
        "Cost per lead",
        "Total likes",
        "Impressions",
        "Follower count"
      ]
    },
    {
      "question": "200 people visit a landing page and 10 book a call. What's the conversion rate?",
      "options": [
        "5%",
        "2%",
        "10%",
        "20%"
      ]
    },
    {
      "question": "Before uploading a data export to an AI tool, you should:",
      "options": [
        "Merge cells to make it easier to read",
        "Delete the column headers",
        "Remove personal information like names, emails and phone numbers",
        "Add as many columns as possible"
      ]
    },
    {
      "question": "An AI tool reports a surprising number from your data. What should you do?",
      "options": [
        "Share it with the team immediately",
        "Assume it's correct because AI is good at math",
        "Delete the data and start over",
        "Ask it to explain the calculation and spot-check the number yourself"
      ]
    },
    {
      "question": "What makes a good A/B test?",
      "options": [
        "Stopping as soon as one version gets a few more clicks",
        "Changing everything at once to find a winner faster",
        "Changing one thing at a time and waiting for enough data",
        "Testing without a hypothesis"
      ]
    }
  ],
  "06": [
    {
      "question": "What does it mean to keep a 'human in the loop'?",
      "options": [
        "AI tools must be used by only one person",
        "Customers must approve every post",
        "A person reviews and approves important or customer-facing AI output",
        "A human must type every word"
      ]
    },
    {
      "question": "Which is the strongest reason to start with one small, frequent workflow?",
      "options": [
        "Large workflows are not allowed",
        "It saves real time with low risk while you learn what can go wrong",
        "Small workflows are free on every platform",
        "It avoids having to test anything"
      ]
    },
    {
      "question": "Which prompt part tells the AI what to avoid?",
      "options": [
        "Examples",
        "Constraints",
        "Task",
        "Role"
      ]
    },
    {
      "question": "Which approach is most likely to hurt your search visibility?",
      "options": [
        "Adding first-hand project photos to your pages",
        "Answering real customer questions clearly",
        "Keeping business details consistent across the web",
        "Publishing hundreds of thin, near-identical AI pages"
      ]
    },
    {
      "question": "What's the best use of AI for audience research?",
      "options": [
        "Guessing what competitors' customers want",
        "Finding common questions and exact phrases in anonymized reviews and customer messages",
        "Inventing customer personas without any real data",
        "Writing fake reviews to test reactions"
      ]
    },
    {
      "question": "Customer lifetime value (LTV) compared with customer acquisition cost (CAC) should be:",
      "options": [
        "Lower than CAC",
        "Unrelated to CAC",
        "Exactly equal to CAC",
        "Much higher than CAC in a healthy business"
      ]
    },
    {
      "question": "What should a weekly marketing report lead to?",
      "options": [
        "A chart of follower growth only",
        "Nothing — it's just for records",
        "The longest possible list of metrics",
        "Specific decisions and actions for the next week"
      ]
    },
    {
      "question": "A website chat assistant answers customer questions. What's required for responsible use?",
      "options": [
        "Hide it from the privacy policy",
        "Pretend it's a real employee",
        "Let it promise discounts on its own",
        "Make clear it's automated and give an easy way to reach a person"
      ]
    },
    {
      "question": "Which statement about AI tools is true?",
      "options": [
        "They always check facts before answering",
        "They produce text that sounds right but can be wrong, so claims must be verified",
        "They know everything about your business automatically",
        "Their output never needs editing"
      ]
    },
    {
      "question": "What is the purpose of a North Star metric?",
      "options": [
        "To measure social media likes",
        "To focus the team on the one number that best represents current success",
        "To replace all other metrics",
        "To track as many numbers as possible"
      ]
    }
  ]
};
