import type { Lang } from './types';

// Words the visitor sees on a customer's page, in the page's language.
const STRINGS = {
  en: {
    saveContact: 'Save contact',
    call: 'Call',
    text: 'Text',
    email: 'Email',
    share: 'Share',
    copied: 'Link copied',
    shareBack: 'Share your info',
    shareBackWith: (name: string) => `Share your contact with ${name}`,
    name: 'Name',
    phone: 'Phone',
    note: 'Message (optional)',
    send: 'Send',
    sent: 'Sent. Thanks!',
    error: 'Something went wrong. Try again.',
    reviewTitle: 'Enjoyed your visit?',
    reviewCta: 'Leave us a Google review',
    reviewAsk: 'How was your experience?',
    reviewThanks: 'Thank you! Would you share it on Google?',
    reviewSorry: 'Sorry we missed the mark. Tell us what happened and we’ll make it right.',
    reviewPrivate: 'Send feedback to the owner',
    reviewOr: 'You can also post a public review:',
    code: 'Code',
    expires: 'Ends',
    badge: 'Get your own tap card',
    notFound: 'This page isn’t set up yet.',
  },
  es: {
    saveContact: 'Guardar contacto',
    call: 'Llamar',
    text: 'Mensaje',
    email: 'Email',
    share: 'Compartir',
    copied: 'Enlace copiado',
    shareBack: 'Comparte tus datos',
    shareBackWith: (name: string) => `Comparte tu contacto con ${name}`,
    name: 'Nombre',
    phone: 'Teléfono',
    note: 'Mensaje (opcional)',
    send: 'Enviar',
    sent: 'Enviado. ¡Gracias!',
    error: 'Algo salió mal. Inténtalo de nuevo.',
    reviewTitle: '¿Te gustó tu visita?',
    reviewCta: 'Déjanos una reseña en Google',
    reviewAsk: '¿Cómo fue tu experiencia?',
    reviewThanks: '¡Gracias! ¿La compartirías en Google?',
    reviewSorry: 'Lamentamos no haber cumplido. Cuéntanos qué pasó y lo solucionaremos.',
    reviewPrivate: 'Enviar comentario al dueño',
    reviewOr: 'También puedes publicar una reseña:',
    code: 'Código',
    expires: 'Termina',
    badge: 'Consigue tu propia tarjeta',
    notFound: 'Esta página aún no está lista.',
  },
  pt: {
    saveContact: 'Salvar contato',
    call: 'Ligar',
    text: 'Mensagem',
    email: 'Email',
    share: 'Compartilhar',
    copied: 'Link copiado',
    shareBack: 'Compartilhe seus dados',
    shareBackWith: (name: string) => `Compartilhe seu contato com ${name}`,
    name: 'Nome',
    phone: 'Telefone',
    note: 'Mensagem (opcional)',
    send: 'Enviar',
    sent: 'Enviado. Obrigado!',
    error: 'Algo deu errado. Tente novamente.',
    reviewTitle: 'Gostou da visita?',
    reviewCta: 'Deixe uma avaliação no Google',
    reviewAsk: 'Como foi sua experiência?',
    reviewThanks: 'Obrigado! Pode compartilhar no Google?',
    reviewSorry: 'Sentimos muito. Conte o que aconteceu e vamos resolver.',
    reviewPrivate: 'Enviar comentário ao dono',
    reviewOr: 'Você também pode publicar uma avaliação:',
    code: 'Código',
    expires: 'Termina',
    badge: 'Tenha seu próprio cartão',
    notFound: 'Esta página ainda não está pronta.',
  },
};

export type CardStrings = (typeof STRINGS)['en'];

export function cardStrings(lang: Lang | undefined): CardStrings {
  return STRINGS[lang ?? 'en'] ?? STRINGS.en;
}
